import typing_extensions

from openapi_client.apis.tags import TagValues
from openapi_client.apis.tags.api import Api
from openapi_client.apis.tags.firewall_api import FirewallApi
from openapi_client.apis.tags.api_api import APIApi
from openapi_client.apis.tags.kubernetes_api import KubernetesApi
from openapi_client.apis.tags.s3_api import S3Api
from openapi_client.apis.tags.ssh_api import SSHApi
from openapi_client.apis.tags.vpc_api import VPCApi

TagToApi = typing_extensions.TypedDict(
    'TagToApi',
    {
        TagValues.CYRILLIC_CAPITAL_LETTER_ACYRILLIC_SMALL_LETTER_KACYRILLIC_SMALL_LETTER_KACYRILLIC_SMALL_LETTER_ACYRILLIC_SMALL_LETTER_UCYRILLIC_SMALL_LETTER_ENCYRILLIC_SMALL_LETTER_TE: Api,
        TagValues._: Api,
        TagValues.CYRILLIC_CAPITAL_LETTER_BECYRILLIC_SMALL_LETTER_ACYRILLIC_SMALL_LETTER_ELCYRILLIC_SMALL_LETTER_ACYRILLIC_SMALL_LETTER_ENCYRILLIC_SMALL_LETTER_ESCYRILLIC_SMALL_LETTER_ICYRILLIC_SMALL_LETTER_ERCYRILLIC_SMALL_LETTER_OCYRILLIC_SMALL_LETTER_VECYRILLIC_SMALL_LETTER_SHCHACYRILLIC_SMALL_LETTER_ICYRILLIC_SMALL_LETTER_KACYRILLIC_SMALL_LETTER_I: Api,
        TagValues.CYRILLIC_CAPITAL_LETTER_DECYRILLIC_SMALL_LETTER_OCYRILLIC_SMALL_LETTER_EMCYRILLIC_SMALL_LETTER_IECYRILLIC_SMALL_LETTER_ENCYRILLIC_SMALL_LETTER_YERU: Api,
        TagValues.CYRILLIC_CAPITAL_LETTER_OCYRILLIC_SMALL_LETTER_BECYRILLIC_SMALL_LETTER_ERCYRILLIC_SMALL_LETTER_ACYRILLIC_SMALL_LETTER_ZECYRILLIC_SMALL_LETTER_YERU: Api,
        TagValues.CYRILLIC_CAPITAL_LETTER_PECYRILLIC_SMALL_LETTER_OCYRILLIC_SMALL_LETTER_CHECYRILLIC_SMALL_LETTER_TECYRILLIC_SMALL_LETTER_A: Api,
        TagValues.FIREWALL: FirewallApi,
        TagValues.CYRILLIC_CAPITAL_LETTER_PECYRILLIC_SMALL_LETTER_ERCYRILLIC_SMALL_LETTER_OCYRILLIC_SMALL_LETTER_IECYRILLIC_SMALL_LETTER_KACYRILLIC_SMALL_LETTER_TECYRILLIC_SMALL_LETTER_YERU: Api,
        TagValues._API: APIApi,
        TagValues.KUBERNETES: KubernetesApi,
        TagValues.S3: S3Api,
        TagValues.SSH: SSHApi,
        TagValues.VPC: VPCApi,
    }
)

tag_to_api = TagToApi(
    {
        TagValues.CYRILLIC_CAPITAL_LETTER_ACYRILLIC_SMALL_LETTER_KACYRILLIC_SMALL_LETTER_KACYRILLIC_SMALL_LETTER_ACYRILLIC_SMALL_LETTER_UCYRILLIC_SMALL_LETTER_ENCYRILLIC_SMALL_LETTER_TE: Api,
        TagValues._: Api,
        TagValues.CYRILLIC_CAPITAL_LETTER_BECYRILLIC_SMALL_LETTER_ACYRILLIC_SMALL_LETTER_ELCYRILLIC_SMALL_LETTER_ACYRILLIC_SMALL_LETTER_ENCYRILLIC_SMALL_LETTER_ESCYRILLIC_SMALL_LETTER_ICYRILLIC_SMALL_LETTER_ERCYRILLIC_SMALL_LETTER_OCYRILLIC_SMALL_LETTER_VECYRILLIC_SMALL_LETTER_SHCHACYRILLIC_SMALL_LETTER_ICYRILLIC_SMALL_LETTER_KACYRILLIC_SMALL_LETTER_I: Api,
        TagValues.CYRILLIC_CAPITAL_LETTER_DECYRILLIC_SMALL_LETTER_OCYRILLIC_SMALL_LETTER_EMCYRILLIC_SMALL_LETTER_IECYRILLIC_SMALL_LETTER_ENCYRILLIC_SMALL_LETTER_YERU: Api,
        TagValues.CYRILLIC_CAPITAL_LETTER_OCYRILLIC_SMALL_LETTER_BECYRILLIC_SMALL_LETTER_ERCYRILLIC_SMALL_LETTER_ACYRILLIC_SMALL_LETTER_ZECYRILLIC_SMALL_LETTER_YERU: Api,
        TagValues.CYRILLIC_CAPITAL_LETTER_PECYRILLIC_SMALL_LETTER_OCYRILLIC_SMALL_LETTER_CHECYRILLIC_SMALL_LETTER_TECYRILLIC_SMALL_LETTER_A: Api,
        TagValues.FIREWALL: FirewallApi,
        TagValues.CYRILLIC_CAPITAL_LETTER_PECYRILLIC_SMALL_LETTER_ERCYRILLIC_SMALL_LETTER_OCYRILLIC_SMALL_LETTER_IECYRILLIC_SMALL_LETTER_KACYRILLIC_SMALL_LETTER_TECYRILLIC_SMALL_LETTER_YERU: Api,
        TagValues._API: APIApi,
        TagValues.KUBERNETES: KubernetesApi,
        TagValues.S3: S3Api,
        TagValues.SSH: SSHApi,
        TagValues.VPC: VPCApi,
    }
)
