# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from openapi_client.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    CYRILLIC_CAPITAL_LETTER_ACYRILLIC_SMALL_LETTER_KACYRILLIC_SMALL_LETTER_KACYRILLIC_SMALL_LETTER_ACYRILLIC_SMALL_LETTER_UCYRILLIC_SMALL_LETTER_ENCYRILLIC_SMALL_LETTER_TE = "Аккаунт"
    _ = "Облачные серверы"
    CYRILLIC_CAPITAL_LETTER_BECYRILLIC_SMALL_LETTER_ACYRILLIC_SMALL_LETTER_ELCYRILLIC_SMALL_LETTER_ACYRILLIC_SMALL_LETTER_ENCYRILLIC_SMALL_LETTER_ESCYRILLIC_SMALL_LETTER_ICYRILLIC_SMALL_LETTER_ERCYRILLIC_SMALL_LETTER_OCYRILLIC_SMALL_LETTER_VECYRILLIC_SMALL_LETTER_SHCHACYRILLIC_SMALL_LETTER_ICYRILLIC_SMALL_LETTER_KACYRILLIC_SMALL_LETTER_I = "Балансировщики"
    CYRILLIC_CAPITAL_LETTER_DECYRILLIC_SMALL_LETTER_OCYRILLIC_SMALL_LETTER_EMCYRILLIC_SMALL_LETTER_IECYRILLIC_SMALL_LETTER_ENCYRILLIC_SMALL_LETTER_YERU = "Домены"
    CYRILLIC_CAPITAL_LETTER_OCYRILLIC_SMALL_LETTER_BECYRILLIC_SMALL_LETTER_ERCYRILLIC_SMALL_LETTER_ACYRILLIC_SMALL_LETTER_ZECYRILLIC_SMALL_LETTER_YERU = "Образы"
    CYRILLIC_CAPITAL_LETTER_PECYRILLIC_SMALL_LETTER_OCYRILLIC_SMALL_LETTER_CHECYRILLIC_SMALL_LETTER_TECYRILLIC_SMALL_LETTER_A = "Почта"
    FIREWALL = "Firewall"
    CYRILLIC_CAPITAL_LETTER_PECYRILLIC_SMALL_LETTER_ERCYRILLIC_SMALL_LETTER_OCYRILLIC_SMALL_LETTER_IECYRILLIC_SMALL_LETTER_KACYRILLIC_SMALL_LETTER_TECYRILLIC_SMALL_LETTER_YERU = "Проекты"
    _API = "Токены API"
    KUBERNETES = "Kubernetes"
    S3 = "S3-хранилище"
    SSH = "SSH-ключи"
    VPC = "VPC"
